In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

weather = pd.read_csv('data/weatherauckland_Niwa.csv')
weather.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data/weatherauckland_Niwa.csv'

In [ ]:
weather['Rainfall(mm)'].max()

166.6

In [ ]:
# israin coloum will change to categories as type, base on plants mood
weather['israin'] = weather['Rainfall(mm)'] != 0
weather

Date(NZST)  Rainfall(mm)  Deficit(mm)  Runoff(mm)  Pmsl(hPa)  \
0     2019-01-01 08:00:00           0.0         40.7         0.0     1016.5   
1     2019-01-02 08:00:00           0.6         44.6         0.0     1013.6   
2     2019-01-03 08:00:00           0.0         49.2         0.0     1011.3   
3     2019-01-04 08:00:00           0.0         53.7         0.0     1018.0   
4     2019-01-05 08:00:00           0.0         58.2         0.0     1020.8   
...                   ...           ...          ...         ...        ...   
1692  2023-08-22 09:00:00           0.0          1.1         0.0     1027.3   
1693  2023-08-24 09:00:00           0.0          3.2         0.0     1027.2   
1694  2023-08-25 09:00:00           0.0          4.2         0.0     1028.0   
1695  2023-08-26 09:00:00           0.0          5.3         0.0     1024.9   
1696  2023-08-27 09:00:00           1.2          5.2         0.0     1021.2   

      Pstn(hPa) Tmax(C) Tmin(C) Tgmin(C) Tmean(C)  israin  
0         993.2    25.6    14.3     12.5       20   False  
1         990.5    26.9    16.6     15.8     21.8    True  
2         988.2    24.8      16     13.2     20.4   False  
3         994.4    23.1    13.3     10.2     18.2   False  
4         997.1    22.1     8.4      5.4     15.3   False  
...         ...     ...     ...      ...      ...     ...  
1692     1002.2    15.7      -2     -4.5      6.9   False  
1693     1002.7    13.7     4.6      0.2      9.2   False  
1694     1003.3    13.7     2.3     -0.8        8   False  
1695     1000.5    15.7     4.4      1.7     10.1   False  
1696      997.0    14.7       6      2.7     10.4    True  

[1697 rows x 11 columns]

In [ ]:
weather.shape

(1697, 11)

In [ ]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1697 entries, 0 to 1696
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Date(NZST)    1697 non-null   object 
 1   Rainfall(mm)  1697 non-null   float64
 2   Deficit(mm)   1697 non-null   float64
 3   Runoff(mm)    1697 non-null   float64
 4   Pmsl(hPa)     1697 non-null   float64
 5   Pstn(hPa)     1697 non-null   float64
 6   Tmax(C)       1697 non-null   object 
 7   Tmin(C)       1697 non-null   object 
 8   Tgmin(C)      1697 non-null   object 
 9   Tmean(C)      1697 non-null   object 
 10  israin        1697 non-null   bool   
dtypes: bool(1), float64(5), object(5)
memory usage: 134.4+ KB


In [ ]:
#Unique values in predictor column
weather['israin'].unique()

array([False,  True])

In [ ]:
weather[weather['israin'].isnull()]

Empty DataFrame
Columns: [Date(NZST), Rainfall(mm), Deficit(mm), Runoff(mm), Pmsl(hPa), Pstn(hPa), Tmax(C), Tmin(C), Tgmin(C), Tmean(C), israin]
Index: []

In [ ]:
weather['israin'].value_counts()

israin
True     875
False    822
Name: count, dtype: int64

In [ ]:
weather['Date(NZST)'] = pd.to_datetime('2022-12-27')
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1697 entries, 0 to 1696
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   Date(NZST)    1697 non-null   datetime64[ns]
 1   Rainfall(mm)  1697 non-null   float64       
 2   Deficit(mm)   1697 non-null   float64       
 3   Runoff(mm)    1697 non-null   float64       
 4   Pmsl(hPa)     1697 non-null   float64       
 5   Pstn(hPa)     1697 non-null   float64       
 6   Tmax(C)       1697 non-null   object        
 7   Tmin(C)       1697 non-null   object        
 8   Tgmin(C)      1697 non-null   object        
 9   Tmean(C)      1697 non-null   object        
 10  israin        1697 non-null   bool          
dtypes: bool(1), datetime64[ns](1), float64(5), object(4)
memory usage: 134.4+ KB


In [ ]:
weather=weather.drop(['Date(NZST)', 'israin'],axis=1)

# Heatmap for correlation between variables
import seaborn as sns

# Select only the numeric columns from the 'weather' DataFrame
numeric_columns = weather.select_dtypes(include=[np.number])

plt.figure(figsize=(8, 8))
sns.heatmap(weather.corr(), annot=True)
plt.show()


ValueError: could not convert string to float: '-'

<Figure size 800x800 with 0 Axes>

In [ ]:
#Heatmap for correlation between variables
import seaborn as sns
plt.figure(figsize=(8, 8))
sns.heatmap(weather.corr(),annot=True)

ValueError: could not convert string to float: '-'

<Figure size 800x800 with 0 Axes>

#TMIN and TMAX are highly positively correlated to each other as observed from above correlation matrix.

In [ ]:
# Features (X) and target variable (y)
features = ['Deficit(mm)', 'Runoff(mm)', 'Pmsl(hPa)', 'Pstn(hPa)', 'Tmax(C)', 'Tmin(C)', 'Tgmin(C)', 'Tmean(C)']
target = 'Rainfall(mm)'

X = weather[features]
y = weather[target]

In [ ]:
#Splitting train and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [ ]:
#Default Random forest classifier
from sklearn.ensemble import RandomForestClassifier
model =RandomForestClassifier()

In [ ]:
#Fitting train data into model
model.fit(X_train,y_train)

ValueError: Input y contains NaN.

In [ ]:
# Make predictions
predictions = model.predict(X_test)

# Evaluate the model (you can choose a different metric if needed)
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, predictions)
print(f"Mean Squared Error: {mse}")

In [ ]:
# Printing confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,predictions))

[[3108    0]
 [   0 3138]]


In [ ]:
#Classification report
from sklearn import metrics
print(metrics.classification_report(y_test, predictions))

              precision    recall  f1-score   support

       False       1.00      1.00      1.00      3108
        True       1.00      1.00      1.00      3138

    accuracy                           1.00      6246
   macro avg       1.00      1.00      1.00      6246
weighted avg       1.00      1.00      1.00      6246



In [ ]:
#Feature Importance
model.feature_importances_

array([0.5059247 , 0.00229308, 0.00799729, 0.00152762, 0.48225731])